classdef PDelay < audioPlugin
  
  %public properties (changable)
  properties        
    Delay = 323; % parameters
    Gain = 0.5; 
    Width = 1;
    Pan = 0;
    Mix = 0.5;
    Bypass = false; %on/off
  end
  
  %plugin customization (hidden)
  properties (Constant)
    PluginInterface = audioPluginInterface('PluginName','Pong Delay',...
      audioPluginParameter('Delay', ...
                            'Label','ms', ...
                            'Mapping', {'int',44,800}, ...
                            'Style', 'rotaryknob', ...
                            'Layout', [2,2], ...
                            'DisplayName','Delay','DisplayNameLocation','Above'), ...
     audioPluginParameter('Gain', ...
                            'Mapping', {'lin',0,1}, ...
                            'Style', 'rotaryknob', ...
                            'Layout', [2,4], ...
                            'DisplayName','Feedback','DisplayNameLocation','Above'), ...
     audioPluginParameter('Width', ...
                            'Mapping', {'lin',0,1}, ...
                            'Style', 'rotaryknob', ...
                            'Layout', [2,6], ...
                            'DisplayName','Width','DisplayNameLocation','Above'), ...
     audioPluginParameter('Pan', ...
                            'Mapping', {'int',-100,100}, ...
                            'Style', 'hslider', ...
                            'Layout', [4,4], ...
                            'DisplayName','Pan','DisplayNameLocation','Above'), ...
     audioPluginParameter('Mix', ...
                            'Mapping', {'lin',0,1}, ...
                            'Style', 'hslider', ...
                            'Layout', [4,6], ...
                            'DisplayName','Wet-Dry','DisplayNameLocation','Above'), ...   
     audioPluginParameter('Bypass', ...
                            'Style', 'vrocker', ...
                            'Layout', [4,2], ...
                            'DisplayNameLocation','none'), ...                             
     audioPluginGridLayout('RowHeight',[20,200,20,100,20,200,20,200,20,200], ...                                     
                            'ColumnWidth',[20,200,20,200,20,200,20,200,20,200]));
  end

  properties (Access=private)
     Fs = 44.1e3;
     Buffer1
     Buffer2
     Index1 = 1;
     Index2 = 1;
  end

  methods
      %set buffer size to maximum size of delay 
      function obj = PDelay()
          obj.Buffer1 = zeros(fix(800 / 1000 * obj.Fs), 1);
          obj.Buffer2 = zeros(fix(800 / 1000 * obj.Fs), 1);
      end

      function out = process(obj, in)
        obj.Fs = getSampleRate(obj);
          if obj.Bypass
          
          [out, obj.Buffer1, obj.Buffer2, obj.Index1, obj.Index2] = pdelayRT(in,obj.Fs,obj.Delay,obj.Gain,obj.Width,obj.Pan,obj.Mix, obj.Buffer1,obj.Buffer2,obj.Index1,obj.Index2);
          return;
          end
          out = in;
      end

      % initialize internal state
      function reset(obj)
          obj.Fs = getSampleRate(obj);
          obj.Buffer1 = zeros(fix(800 / 1000 * obj.Fs), 1);
          obj.Buffer2 = zeros(fix(800 / 1000 * obj.Fs), 1);
          obj.Index1 = 1;
          obj.Index2 = 1;
      end

  end
end